apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-secrets
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-configmaps
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-secrets
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-secrets
subjects:
- kind: ServiceAccount
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-configmaps
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-configmaps
subjects:
- kind: ServiceAccount
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
{{- /*
Install ClusterRoles, when namespace is not set. Otherwise use "local" Roles 
*/ -}}
{{- if .Values.watchNamespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-services
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnservices
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
{{- /*
Install ClusterRoles, when namespace is not set. Otherwise use "local" Roles 
*/ -}}
{{- if .Values.watchNamespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-projects
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
{{- /*
Install ClusterRoleBinding, when namespace is not set. Otherwise use "local" RoleBinding.
*/ -}}
{{- if .Values.watchNamespace }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-projects
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keptn-gitops-operator.serviceAccountName" . }}
    {{- if not .Values.watchNamespace }}
    namespace: {{ .Release.Namespace }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.watchNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-projects

---
apiVersion: rbac.authorization.k8s.io/v1
{{- /*
Install ClusterRoleBinding, when namespace is not set. Otherwise use "local" RoleBinding.
*/ -}}
{{- if .Values.watchNamespace }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-services
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keptn-gitops-operator.serviceAccountName" . }}
    {{- if not .Values.watchNamespace }}
    namespace: {{ .Release.Namespace }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.watchNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-services
