# permissions for end users to view keptnservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnservice-viewer-role
rules:
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnservices/status
  verbs:
  - get
