# permissions for end users to edit keptnprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnproject-editor-role
rules:
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects/status
  verbs:
  - get
