# permissions for end users to view keptnprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnproject-viewer-role
rules:
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects/status
  verbs:
  - get
