
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptngitconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptngitconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptngitconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects/finalizers
  verbs:
  - update
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnservices/finalizers
  verbs:
  - update
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories/status
  verbs:
  - get
