
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.keptn.sh
  resources:
  - keptngitopsrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.keptn.sh
  resources:
  - keptngitopsrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - operator.keptn.sh
  resources:
  - keptngitopsrepositories/status
  verbs:
  - get
  - patch
  - update
